name: Deploy CodeIgniter4 to Host

on:
  push:
    branches:
      - main  # deploy when you push to main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sync Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./         # root of your repo
          server-dir: /htdocs/my_app  # your custom folder
          git-ftp-args: --insecure
